---
title: "Recapping the first two months"
author: "Jacquie Tran"
date: "2011-02-09"
categories:
  - phd
---

Time has flown since I officially started working on my PhD, back in November 2010. Apparently I've also filled my head with all sorts of knowledge and memories and other useful or useless things, because it was a nice surprise to revisit my earlier PhD-related blog posts. Here’s a recap of how things have unfolded from my earlier musings...

## The Four-Day Work Week

This is going really well so far. Giving myself day/time limits helps to keep me focused, even when I'm not feeling "locked in". Thursdays are my "end of working week", so it's never very far away, even if it's only Monday. This time limit gives me a lot of momentum to get going, and as a result, I feel like I'm being more productive with my time. I've been able to meet all deadlines thus far, including the submission of two ethics applications. I am remaining aware of the fact that I don't even know what busy really means yet, but who knows how long I'll be able to keep up four-day work weeks during really insane periods of deadlines and external pressures? So I figure I might as well take advantage of these "quiet" periods to keep myself sane :)

It's also a nice feeling to finish work for the day, because I leave it all in the office. During Honours, I worked from home a lot, which suited my night-owl body clock (wake up somewhere between 10–11 AM, get started on work at 2 PM, work until 8–10 PM), though in retrospect I did battle regularly against procrastinating activities (aka THE ENTIRE INTERNET). Now, I quite enjoy the separation of sitting at my office computer to work, and sitting on my home PC for enjoyment.

Also...three-day weekend, baby. Every weekend. BOOM.

## Distraction time

Blocking out a period of my work day for distraction time has actually relieved a sense of guilt that I wasn't aware I was retaining. I fill this time with various activities, such as short walks around campus, trotting off for coffee, chats with friends and office colleagues about nothing in particular, stretching and postural work, social media, and reading up on the news.

I set time limits for these activities, and I stick to them, feeling refreshed and able to re-focus quickly once distraction time is over.
