---
title: "Moar words"
author: "Jacquie Tran"
date: "2011-06-04"
categories:
  - phd
  - phd writing
---

1,000 quality words "on paper" today. YEOW!

I really wasn't happy with my first draft, as it was only partly-referenced but mostly a composite of my 10-minute free writing bursts. But I'm trying (very hard) to stop beating myself up about it because [everyone's first drafts are crappy](https://thesiswhisperer.com/2011/06/02/another-way-to-write-1000-words-a-day/), right? (protip: click that link...*"The Thesis Whisperer"* is one of my favourite PhD blogs!)

Still, my distaste for the quality of my first draft was getting in the way of me making decent changes for my second draft. Something told me I would be happier with a blank file and starting my writing again "from scratch" (in a new file). But I was having trouble detaching myself from the work I'd already done, until I briefly caught up with my dear friend Gill, who always tells it to me straight. I told her of my blank paper plan (that had not yet been acted upon). Her (paraphrased) response? "So just do it. You’re not *really* dumping the work you’ve already done..."

Today I did it. I opened up Word, started with a fresh new file, and copied over only my headings and subheadings from section one of my lit review. It took me the whole day, but now I have section one written and out of the way and I'm really happy with it. I'm only wishing now that I'd been brave enough to do this a week ago! You live, you learn :)

At this stage, I'm aiming to submit the second draft on Thursday to le supervisors, which will definitely be challenging. I may need to extend that deadline so I can do justice to the research proposal as well.
