---
title: "Good news :D"
author: "Jacquie Tran"
date: "2011-05-03"
categories:
  - phd
  - phd writing
---

I found out that I only need to write 10,000 words total for my written confirmation document. So by default, I am 2000 words in the bonus...sweet! I am breaking the 10k down into:

- Literature review = 6,000 words
- Research proposal (methodology) = 3,000 words (~1,000 words per study)
- Research plan = 1,000 words

Right now, my lit review is at ~4,600 words. The bones are there but I'm having trouble getting the structure right - meeting with my supervisor tomorrow, and I think his recommendation is going to be to chop the "background info" sections out completely or condense them down into one or two sentences. Sigh. Methodology section needs some refining, but it's at about 1,500 words without really trying too hard, and having written substantially more on my first up study than studies two and three. The research plan is a pretty straightforward document that doesn't require nearly as much clean, flowing prose as the other two components, so I'm going to try to knock that out tomorrow.
