project:
  type: website

website:
  title: "Hidden Labours | An archive of an old blog from my PhD times"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css

editor: source

