project:
  type: website

website:
  title: "Hidden Labours | An archive of old blog posts from my PhD+ times"
  
format:
  html:
    theme: lux
    css: styles.css
    highlight-style: github

editor: source

