---
title: "To start: A confession"
author: "Jacquie Tran"
date: "2011-07-02"
categories:
  - beginnings
  - phd
---

I've already past the six-month mark of my PhD and have been blogging about it all this time, over at my [Tumblr](http://jaccccc.tumblr.com/tagged/phd). (It feels a little dirty to link to my Tumblog in the first sentence of my first WordPress post!)

You're probably wondering, *"After six months of PhD blogging, why the change of format?"*

It's more or less about separating out things according to my thoughts about what is Tumblr-friendly and what is WordPress-friendly. Though I have strayed from the model many times, I still think of my Tumblr as a place to capture snapshots: in photos, videos, songs; of short quotes and emotional responses "in the moment". I like how the format encourages content generation straight from one’s stream of consciousness, and discourages long posts (read: posts with more than one paragraph). Both of these things are good for me; I am inclined to overthinking and rambling. On the other hand, the more I blog about my life as a PhD student, the more I find that certain pieces don’t quite fit the Tumblr mould.

Given the test run over the last six months, I've decided to launch this blog, where I will be posting more considered posts about my PhD experience. I’ll still be posting about the PhD on Tumblr, but you should know upfront that I can be highly personal, emotional and impassioned over there (often all at once). Also, as it is my personal blog, there’s plenty on there that is irrelevant to my academic pursuits. You have been forewarned 😉
