---
title: "bump in the road"
author: "Jacquie Tran"
date: "2011-02-17"
categories:
  - phd
  - productivity
---

It's fair to say that I haven't been as productive as I would have liked this week. A couple things that have happened this week:

- I've been sleeping 10+ hours per night, and have finding it a bit more difficult than usual to wake up in the mornings. For me, this isn't really too worrying as I am a heavy sleeper and always find it hard in the mornings (inb4 #TWSS). But my sleep behaviour this week is a little bit out of the ordinary, as I have generally been in bed before midnight, which is early for me, and don't feel as though I am sick or exhausted or run-down in any way. I have a feeling that it's related to a change in my training cycle this month, with more moderate- and high-intensity sessions, so it could just be my body adapting to this new cycle and recovering from training.
- The consequence of my sleeping marathons this week was that I just didn't spend a whole lot of time at uni. After dragging myself out of bed, having breakfast, and finally leaving home, I arrived at uni somewhere around 11 AM–12 PM every day this week. Ordinarily, I would have just extended my day at the other end, perhaps working until 7 PM or so. However, I've had a lot of weeknight engagements this week so I've been knocking off at 5ish, feeling a little guilty and unfulfilled from the small amount of work I've been getting through.

I'm also at a stage where the work in front of me is not my favourite work...reading and annotating articles until FOREVER. It's a necessary part of any research, but that doesn't make it more fun for me. Like it or lump it, it's just something I have to keep pushing myself to do.

I've also had a few other things on my mind that have distracted me this week. Next week will likely be shortened as I'm roadtripping it to finish off February :) To make up for lost time, I'’'ll be dropping in tomorrow for a Friday afternoon at uni (that's my flexible Friday coming in handy in my 4-day workweek), and may also drop in on Saturday morning as well.
