---
title: "Making the link between creativity and my academic approach"
author: "Jacquie Tran"
date: "2011-02-28"
categories:
  - phd
  - creativity
  - reflection
  - systems
  - workflow
---

Fortunate enough to know what work I want to do. Fortunate to be in a position (financially, socioeconomically, and educationally speaking) where I can pursue, on a full-time basis, work that engages me. Fortunate to be good enough at this work to meet my personal standards. Most days, I feel awfully lucky to be in the position I am in.

But something that has confused me for a long time is the way I can feel so passionately about two very different streams in my life: 1) my creative pursuits, and 2) my work as a developing sport scientist. In my mind, I've always separated out these two supposedly disparate branches, without really giving thought to the opportunities for the two to come together and create something even greater. Because really, how natural does it feel to think about music *and* sport, compared to music *or* sport?

At 15 or 16, I decided sport science was what I wanted to do. I came to the realisation that sport science was an area of study that I found intellectually-stimulating, socially-relevant, and aligned with my interest and involvement in sports. A part of me also concluded that chasing this dream meant giving up another. You know that dream so many of us have of becoming rock stars? Or in my case, a songwriter, or composer, or session musician, or simply a music-maker by any other name? I gave up on those distant possibilities to set sail towards becoming a sport scientist. It's not a decision I made lightly, but also not a decision I've ever regretted because I always saw my dual passions as **mutually exclusive**. I knew that, one day, I would have to choose one favourite between my two children, so to speak ;)

Now at 22 and wading through the early stages of a PhD in sports performance analysis, I am starting to make the mental link between my life as a scientist and a student, and my life as a creative. Almost everyday, and certainly every week, **I am learning more about how I learn**. And in every instance, the relationship between my creative side and my scientific side becomes clearer. I am now beginning to conceptualise the **co-existence** of my two great loves.

At this stage, the lean is towards how my creative side supports and actually underpins most all of the academic work I do. (Consequently, it makes me excited that I might someday figure out how my scientific and scholarly pursuits inform me as a creative!) I am establishing systems to support my achievement of Great Work. What I am noticing is my blatant attraction to that which can help me complete [**Great Work**](http://web.archive.org/web/20110221070022/http://zenhabits.net/kill-busywork/) efficiently, while also being visually stunning, creatively inspiring, and emotionally connected to my self-concept.

I also find that I am becoming less interested in what people in my own field do to become (or be considered) "successful". More often, I gravitate towards the stories and journeys of writers, poets, designers, painters, musicians, photographers. I relate far more to these artists, these observers of the human spirit and condition, than I do to your typical straight-line, no-nonsense scholar or academic.

More on specific workflows and inspirations in blog posts to come, but I just felt compelled to write about what I feel is an emerging relationship between my personal artistry and scientific study. Consider it the influence of my muse dropping by for a late night visit. :)
