---
title: "Lit review draft v2.0 submitted!"
author: "Jacquie Tran"
date: "2011-06-16"
categories:
  - phd
  - phd writing
---

3:30 AM. I have spent most of the last few hours trying to get rid of some adware/malware that jumped onto my system instead of, you know, actually working on my confirmation documents. Blerg!

Nevermind. I just emailed the second draft of my literature review to my supervisors, missing sections and all. But I'm not overly concerned. I decided to leave content out entirely for those sections rather than copy and paste from my first draft because the blank doc approach has been working really super well for the flow in my writing. Also, my first draft was more like a *shit review*...this draft is in far better shape, and I know the currently blank sections will be better if I take the time to respect the story I am trying to tell.

Aiming to have the second draft of my research proposal to them by Friday. Still pressing for an end of June final deadline for the document, though a part of me has been thinking that it is unlikely because it doesn't give my supervisors enough time to read my drafts and give feedback. Normally, I allow for a two to three week waiting period for draft feedback, but if I want this doc done by the end of June then I don't have that leeway.

Team meeting tomorrow; we shall see what the big wigs have to say! But for now...bed :)
