---
title: "Backwards to go forwards"
author: "Jacquie Tran"
date: "2011-05-13"
categories:
  - phd
  - phd writing
---

Since my last post on the progress of my confirmation documents and my breach of the four day work week pledge, I have done very little additional work on the project. Naturally.

I've felt constrained by my lack of reading, the result of which is that my well of thoughts has run dry this week. I've lacked energy for the task because, aside from word count, I have little to indicate whether I've put in a good day’s work. So it's back into the lit for me...an easily measured task, and one that will hopefully tip some fresh ideas into the well :)

T'were it that easy, I'd be laughing! I also have to prepare for next week's very important trip interstate. I'll be retrieving retrospective data, presenting my proposed research direction to my project co-investigators, and asking too many questions about testing and data collection protocols.

Honestly, I feel a bit nervous about the trip, because I feel unprepared. The trip is also being funded by two institutions so I feel the pressure to make it count. My remedy is to remind myself how well I work under pressure... ;)
