---
title: "3:30-itis"
author: "Jacquie Tran"
date: "2010-12-09"
categories:
  - phd
---

In my second week of coming in to uni three to four days per week, I am noticing a trend in my concentration levels. Specifically, the 3:30–4:30 PM time slot kills me. I lose focus as people around me start getting ready to close up shop for the day. However, as a late riser, I only really get going at about 10 AM, and so I arrive to the office later than others who start up at 8 AM or even earlier than that. At this early stage of my PhD, it hasn't been detrimental to leave "early" at 4–5 PM, but I leave feeling as if I haven't put in a full day's work.

A couple of things this indicates or reinforces for me:

- The traditional notion of putting in 9–5, Monday to Friday, does not suit me. If keeping to my natural sleep patterns, I go to bed somewhere between 12 AM and 2 AM, and will wake up eight hours later. So my general plan is to aim to get into the office at around 10 AM, and I am hoping to average four days a week at the office / working on my PhD (with some flexibility to increase working days per week during periods leading up to important deadlines).
- Over the last two years of uni, I noticed that I was more productive at night. However, I am becoming increasingly reluctant to work from home because I feel like keeping my PhD life at uni will help me make healthy choices with regard to my time (separating time for me from time for work). During Honours, I predominantly worked from home, which suited my two daily productivity cycles, as I often pushed out a lot of my best work around 11 AM to 3 PM, and 8 PM onwards. Will have to make a compromise in this area, as my aim throughout the next three years is to manage my time well enough to get the work done in three years (and not any longer), while also having time for social activities.
- After spending nearly a year completely away from the academic environment, I am still getting to grips with what is required in terms of everyday mental effort. I seem to be getting about 4–5 hours of solid work out of any given day. Hopefully this will continue to improve, or else I'll have to figure out a way to be much more efficient during my limited "focus hours".
- I love naps, and that mid-afternoon time is prime for napping. When I worked from home during Honours, I allowed myself many afternoon naps, but it's not an option when working from the office. Coffee doesn't help here, so the napping difficulties may be explained by my habitual coffee drinking...

And some potential strategies to deal with my 3.30-itis:

- Block out this time to handle things that require small amounts of my concentration for short periods, e.g. responding to and organising emails, organising my workspace, updating mind maps and action plans.
- Designate this period for physical activity: go through my stretching routine, go for a walk, etc.
- Drawing from a suggestion on the [Zen Habits blog](https://zenhabits.net/simplify-your-workday/), designate this period as "distraction time" (which is what I am practising right now!). Blogging, getting up to speed across the social networks, etc.