---
title: "60-Day PhD Writing Challenge Day 7: Make a list of journals; Write for at least 15 minutes"
author: "Jacquie Tran"
date: "2011-06-09"
categories:
  - phd
  - phd tumblr support group
  - phd writing
---

<u>randomrantings</u> (edited to remove dead links as of Dec 2024):

> **Day 7: Make a list of 3-6 journals in your field; write for at least 15 minutes**

Journals in my field that I’d like my work published in, with impact factor*:

- Medicine & Science in Sports and Exercise (3.7)
- Journal of Science and Medicine in Sport (1.6)
- Journal of Sport Sciences (1.6)
- Sports Medicine (3.1)
- Journal of Applied Physiology (3.7)
- Scandinavian Journal of Medicine & Science in Sports (2.3)

Writing is chugging along. Probably spent about 4 total hours concentrating on writing yesterday (including reading time, sorting through refs, rephrasing, etc.), and finished up with about 400+ words to introduce a section. Today's goal is to add another 1000 words to the section. This particular section will probably make up 2000-2500 words by the time it's finished.

* I put impact factors in only because it's something I rarely think about! In my field, impact factors are reasonably low compared to other sciences because the application of science to sport is still a bit of a niche.
