---
title: "Work flows brain dump #2"
author: "Jacquie Tran"
date: "2011-06-06"
categories:
  - phd
  - workflow
---

I like the visual appeal of **minimalism** but I have trouble maintaining that same appeal in my work space. I try to combat my cluttering tendencies by deliberately choosing tools or systems that "penalise" me for not respecting clear, uncluttered space. Here’s a good example: I use Google Chrome because everything about it looks and works better when I do fewer things to the browser. I used to be a Firefox devotee, but it was too easy to hoard links in the bookmark bar, especially with the multi-row bookmark bar extension installed...

**Music is essential.** I will have usually listened to at least one song in the morning before even getting out of bed. Lately it has been "Radar Detector" by [**Darwin Deez**](https://darwindeez.com/), or something off the latest album by [**The Little Stevies**](https://thelittlestevies.com/). Though my drive to work is short (usually 5-10 mins), I always make sure I plug in my iPod or tune into Triple J for the journey. Music helps me focus in my shared office at uni. Even years later, I find I can recall information about tasks I have worked on if I think about what songs or artists I was listening to at the time.

Music is also my release. I can't plug away every single day on the same project without rapidly losing interest and effectiveness. I am prone to bursts of motivation that can extend for a few weeks, but some days I hit a wall and just don't have it in me. So I retreat to somewhere quiet, with as little people traffic as possible, and disappear into the **comfort of music**.

I'm very organised. I don't do anything particularly revolutionary. I've just learned to **commit to a system that works and be prepared to change it if it doesn't work.** The bones are of my system are: a calendar, a to-do list system, and a note management program, and a back up plan. The other key characteristic of my system is that it should be as accessible as possible. **I hate feeling like I am chained to do my work in any one place.** Portable and internet-based applications are a natural fit; Google Calendar, Remember the Milk, Evernote, and Create Synchronicity are core applications within my system.

I'm working on figuring out how to bridge the gap between my inclination to work like a creative while meeting the demands of academic. Current guiding concepts include:

- Perfect is the enemy of done.
- Get to done, then make it better.
- If the work gets done, how the work gets done doesn't matter to anyone else.

That last point is pretty important to me and I will readily disagree with anyone who thinks my work suffers for not conforming to M-F, 9-5 ideals. Further to that, I refuse to consistently work the ridiculous volumes of time that others do in my field, and in academia generally. I've tried it. The work got done, but in my eyes the method itself didn't work. The bottom line is that extreme stress combined with one-eyed devotion to a task compromises my health, my sanity and my capacity to maintain healthy relationships. I am in the privileged position of getting to work at something I really enjoy, but I don't love any of it enough to justify making sacrifices in my wellbeing and relationships. **I've become better at trusting that I am good enough** at what I do to decide how to create my best work.
