---
title: "60-Day PhD Writing Challenge Day 6: Self-reflect on Week 1; Write for at least 15 minutes"
author: "Jacquie Tran"
date: "2011-06-07"
categories:
  - phd
  - phd tumblr support group
  - phd writing
---

<u>randomrantings</u> (edited to remove dead links as of Dec 2024):

> **Day 6: Self-reflect on Week 1; Write for at least 15 minutes**
>
> For today, I'd really like you to share your responses with the group if you feel comfortable.
>
> Today's task: How did Week 1 *really* go for you?
> 
> - What successes did you have?
> - What roadblocks did you face?
> - What feelings arise as you look to the remaining 11 weeks?

It was nice to actually put "pen to paper" on the specific questions that were posed regarding our thoughts and feelings about academic writing. I've thought a lot about the process and chatted to many people about it, but blogging helped crystallise some things for me.

In particular, I had been thinking about "dumping" the work I'd done for the first draft of my lit review/research proposal, and starting afresh with a blank Word doc and the thoughts in my mind. The key part of that sentence is "had been thinking about"...I was just mulling it over in my head, not willing to take the plunge and you know, actually do it.

I didn't do the abstract writing task because it's not really where my headspace is right now, though I intend to start the tasks all over again when I take on a new writing challenge in July (after my confirmation documents are done). Instead, I took the plunge and did the blank doc revision; the weekend produced 1,700+ words. Quality words, too; not an unstructured, repetitive brain dump of ideas.

With still a lot of work ahead of me, the lit review sits at about 2,500 good words. Due to some events external to my PhD, I've shifted my second draft submission date from Thursday of this week to Monday next week. That will still be a big ask but I need to press on if I am to stay on track to complete these docs by the end of June, and earn myself a roadtrip! I feel confident about the lit review, particularly with the strides I've made in the last week. I'm not feeling so assured about the research proposal, as I've been having difficulty nailing down my research questions, so that's a demon I have to confront again this week.
