---
title: "Work flows brain dump #1"
author: "Jacquie Tran"
date: "2011-06-05"
categories:
  - phd
  - workflow
---

<em>I follow a few blogs that I've categorised as "productivity + lifehacks" resources, and while I sometimes find general tips and tricks useful, what I really love to learn about is how specific people work in their specific circumstances.

I've been meaning to write about my own work flows for a few months now, but the post has been sitting in my drafts untouched. I felt compelled to finally get to it after reading about [how Tumblr's David Karp works](https://www.inc.com/magazine/201106/the-way-i-work-david-karp-of-tumblr.html). With the idea fermenting in my head for so long, I have now written words for **days**...so I'm splitting it into parts! It also gives me an excuse to test the Tumblr queue to see if they got that old dog working again...</em>

I am a sport scientist by profession, but I wear many guises on any given day depending on the projects I am actively involved in: **PhD student**, research assistant, tutor/teacher, conditioning coach, corrective exercise practitioner, client communications representative. My work essentially comprises and is supported by two key components: my **creative background** as a musician, some-time stage performer and hobby graphic designer, and the **academic skills** I've developed over recent years.

I'm very **visually-inclined**; I learn and work best when I get to see something either in progress or from start to finish. As you might expect from being heavily involved in sport, I am regularly learning about different, interesting ways to move or measure movement. In this context, I like to see an expert or skilled performer doing the task first, but then my kinaesthetic sense takes over and **I like to move quickly from a demonstration to replicating the performance myself**. I think it helps to watch complex movements in their entirety, but this might be influenced by what I've read about in coaching and motor learning literature.

Though this is my fifth year of tertiary studies in sport science, I feel like I still learn something new on a daily or at least weekly basis, which I think is a great blessing for me as my interest in anything wanes quickly if I don't see or feel progress.

I like bright colours. **I'm the kid that purchases the multi-colour sticky notes over the traditional yellow pads.** I have a shoebox full of colour markers. I think it's mostly because I am highly visual. But I've also thought that it might be a reaction to the "black text on white paper, Times New Roman, 12 pt, double spaced" world of academic submissions.

This year, I've been trying my hand at [sketchnoting](http://www.sketchnotearmy.com/). I'm not great at linear thinking on-the-fly, so I love the freedom it gives me to just think without feeling bound to structure. Class notebook-style lines remind me of linearity, so my favourite notebooks are either unlined or gridded. **Drawing notes instead of writing them is also super fun!** It gives me a great reason to carry a handful of coloured textas with me for "work".

