---
title: "PhD Writing Challenge"
author: "Jacquie Tran"
date: "2011-05-26"
categories:
  - phd
  - phd tumblr support group
---

Thanks <u>randomrantings</u> for setting up the official 60-Day PhD Writing Challenge! *(edited to add: removed dead links as of Dec 2024)*

Guidelines for **ASSIGNMENT #1** for the 60 Day PhD Writing Challenge:

1. Pick what manuscript you want to work on. It can be a new manuscript/revision/thesis/dissertation chapter/lit review, etc. Be sure that the writing project you choose will have a definable end point such as complete article, chapter, or a certain number of words so that you can feel a sense of accomplishment at the end of the 12 weeks.
2. Decide a reward for yourself at the end of the 12 weeks for if you complete the challenge.
3. Decide a fee if you do not meet your writing goal by the end of the 12 weeks.

Here are my responses:

1. I've been working on my **confirmation documents** (literature review, research proposal, research plan, oral presentation, verbal defense) since early April. I'm aiming to have them completed and ready for submission/presentation by June 30. After June 30, I'll decide on a new writing piece to begin work on - probably the first draft of a thesis chapter :)
2. Reward at June 30 if goal is met: **July road trip!** 3-4 days away from it all :)
3. Fee if goal is not met at June 30: **No "lie-ins" for a week.** This happens basically every morning where I wake up and lie in bed for 30–60 mins, indulging my laziness. I enjoy it, but it definitely gets in the way of getting things done sometimes! And having to relinquish this joyous activity as a potential fee will be a strong extrinsic motivator for me, because boy oh boy do I like my bed... #unintentionallydirty

Bring on Monday: Day 1!