---
title: "60-Day PhD Writing Challenge Day 2: Forming positive writing habits"
author: "Jacquie Tran"
date: "2011-05-31"
categories:
  - phd
  - phd tumblr support group
  - phd writing
---

<u>randomrantings</u> (edited to remove dead links as of Dec 2024):

> **DAY 2: Forming positive writing habits**
>
> 1. *Choose a customary writing site.* Form a habit of dedicating this space to your writing. Some have a site to prepare for writing and then another site for actually writing. Also think of a backup writing site in case your regular spot is unavailable. Make any necessary improvements to your site, like cleaning old stacks of paper off your desk, getting an ergonomic chair, etc.
> 2. *Make a writing schedule.* For many of us, we fall into a permanent state of "waiting" to write as in a day on the weekend, in between classes, or that summer break. Then we sit down to write for hours upon hours. No wonder PhD writing becomes a cumbersome task! 

1. For a few months, I was really enjoying the separation of office and home by only doing my PhD work in the office/on campus. However, I have since dubbed my office "distraction central" because it is a shared office. I'm very social, and if there are other people around, my tendency is to chat! So I've been spending a lot of time **working from home** to get through my writing tasks. (I still like the idea of separating home and work in terms of physical as well as mental space, so I think I will have to <em>*gasp*</em> become an early riser to make use of the morning hours when there isn't anybody else around...) At home, I write in two places - either at my computer, or at my study desk with old school pen and paper.
2. I've got a broad writing schedule for my confirmation documents, which says that my current focus should be on rustling up a second draft of my lit review/research proposal, and working on a formal oral presentation. Broadly-speaking, I am goal-driven, and my task system is reasonably well-established. As a result, I don't reference my writing schedule very often, but as a matter of habit, I regularly drop my writing tasks right into my existing system and that seems to be working so far.

Key recurring tasks include: **free writing** (10 mins, 1-3 times on writing days), **reading and annotating articles** (depending on my schedule, I aim to get through 3-6 articles in any one day), **transcribing annotations into Evernote** (it's basically a lot of typing, but as a very visual person, I find it works in some sneaky way to help me remember what I've read), and **section-specific editing**.

Also, the days that I'm actually at uni/working on my PhD vary from week to week, because I just don't like that kind of rigid "M-F, 9-5" structure to my schedule. I aim for four day work weeks, but with my writing deadline only one month away (yikes), I have been averaging five day work weeks and will probably bump that up to six days per week from here until the end of June. Working days can include a weekend day if it strikes me as a good opportunity (it sometimes does!), and this framework gives me the flexibility to take a day off during the traditional working week without guilt, if I feel that's what will help me recharge. Again, with my writing deadline looming, I write or complete tasks that contribute to my writing (e.g., reading and annotating articles, mind mapping) on all working days.
