---
title: "The academic life"
author: "Jacquie Tran"
date: "2011-04-11"
categories:
  - phd
  - teaching
  - career
---

It's a nice feeling to take those scary-but-fun first steps into something new. The feeling is the same for me every time, no matter the domain, the task, the environment... Like singing in front of an audience for the first time, or teaching my first undergraduate class, or running my first true data collection sessions.

Today, I delivered my first guest lecture. It went pretty well, I think! So now I can say that I've lectured to undergrads at a major Australian university. Cool but weird! Especially when I think back to being an undergrad myself, sitting in lecture theatres, trying not to fall asleep...and that was only back in 2008 :) Though it hasn't even been three years since graduating with my Bachelor's degree, I feel pretty far removed from that time in my life. I feel like I've come a long way in a short amount of time.

One of the really great things about continuing into postgraduate education are the opportunities that come about to get involved. There were definitely times during undergrad where I questioned whether I was learning in the best environment, studying at the best uni for my profession. But since Honours, I've done more fun and engaging career-related work than at any time before. Importantly, I've discovered that I am right where I want to be and where I should be.

Not only is it great to be able to volunteer myself for various activities around the school, faculty, and university, but it's so flattering to be asked to take part. I still think of myself as a lowly student, with a little knowledge but so much more to learn. I often forget that I'm already a qualified professional with valuable skills and competencies. Today was a great day and a great way to be reminded of how far I've come.
