---
title: "PhD progress...hello/goodbye Jan 2011..."
author: "Jacquie Tran"
date: "2011-02-02"
categories:
  - phd
  - productivity
---

Now into February, things are going well so far. Ethics has been submitted for the project, and we should hopefully be able to get that approved so we're ready to look at data in March. And aside from last week's small hiccup (falling ill and missing two scheduled work days), I'm feeling pretty motivated, interested, and productive.

Since I last blogged about my productivity levels, I feel like I've definitely improved. At the end of 2010, I felt as though I was struggling to get through 4–5 hours of productive work in a day. Now, I feel like I'm averaging 6 productive hours per day quite easily. My original intention was to schedule my days so that I wake up late (with my normal sleep cycle I wake up naturally around 8:30–9 AM) and roll up to uni at around 10 AM. Right now, my days are pretty consistently 10 AM–5 PM, though I had plans to compensate for my later start time with a later finishing time. However, I am having a bit of a struggle maintaining focus as 5 PM rolls around, as the people around me (within my office and also in the other offices nearby) begin to clock off. So I've been questioning my original stance, and have come to the conclusion that 10 AM–5 PM is just fine for now. Staying until 6–6:30PM for the sake of it wouldn't achieve anything.

With the (mostly) lovely summer weather we've had over the past few weeks, I've also taken the liberty to wander away from my desk for short but regular breaks, and this is definitely helping me stay on task when I do sit down to work.
