---
title: "it starts tomorrow!"
author: "Jacquie Tran"
date: "2010-11-21"
categories:
  - phd
---

though i am not officially a student again just yet, i am considering tomorrow the first day of my phd.

at this stage, i'm just waiting to receive confirmation of enrolment, then we're away! so i don’t have my own workspace yet (not until i'm properly enrolled), or a student card, but that won't stop me from getting the ball rolling. **(p.s., thank you to everyone who sent their congratulations!)**

on trial: four-day work weeks. inspired by tim ferrriss, inventor and proponent of the **"four-hour work week"**. while i think that target is a bit extreme and unrealistic for my purposes, the premise of my four-day week remains the same. my aim is to:

- avoid burnout
- allocate plenty of time for my personal life, away from uni- and work-related engagements
- encourage efficiency and productivity by training myself to better understand "performance over presence"

i have been intrigued by the four-hour work week since i got my hands dirty in a lot of productivity resources last year, during honours. a lot of the work in this area is about making more money with less time-effort, which is an angle that probably moves a lot of books from shelves. but my primary interest is in maintaining life balance.

i've known for years that i am passionate about pursuing sport science as a career. but what i learnt last year was that that passion can also be destructive, either in a professional sense or with respect to the broader picture of the rest of my life. when you love your work, it's really easy to convince yourself that maybe an extra hour or two of work, late into the night, will do your project a world of good. or that you don't deserve to enjoy a night out because you haven't met your weekly goals. or that you should sacrifice time from every other area of your life to meet your career demands. but oftentimes, these compromises don't improve your work; i found myself producing sub-par writing, spending long stretches of time procrastinating, and feeling less than fit and healthy.

nothing is cut and dry, of course, and i'm not saying that i won't ever work six-day weeks, or ever pull another all-nighter again. what i am saying is that i want to achieve more balance. i want to get the most out of my work time, so that i can fully enjoy my time away from it. those who are more ahead of the game than me may have their reservations, but i believe i can make four-day work weeks successful for me over the next few years.

here we go!
