---
title: "60-Day PhD Writing Challenge Day 1: Understanding feelings about writing"
author: "Jacquie Tran"
date: "2011-05-30"
categories:
  - phd
  - phd tumblr support group
  - phd writing
---

<u>randomrantings</u> (edited to remove dead links as of Dec 2024):

> **DAY 1: Understanding feelings about writing**
> 
> According to Belcher, "learning to talk about writing is an important key to becoming a productive writer" (p. 2). The first step to overcoming a writer's block/writing anxiety is to understand your relationship to writing. Hopefully you've picked out a paper to revise, write, or condense. Think about this particular paper. If you haven't no worries! Think about academic writing in general! Then share with the group the answers to the following questions:
> 
> <em>What feelings come up when you think about writing?
> What are some negative feelings that arise?
> What are some positive feelings that arise?</em>
>
> Don't forget to tag your post **#phd tumblr support group**!

1. Thinking about academic writing bores me, to be honest! I am not typically intimidated or nervous about writing academic pieces, but I find it difficult to motivate myself to get going. I think most of it comes from my dislike for the formulaic process that is involved in writing scientific papers (I'm a sport scientist). I write copiously, introspectively, creatively, for my own satisfaction. On the other hand, I view academic pieces as process tasks, things that I must do to achieve a greater aim (the accumulation and then practical application of knowledge).

2. Boring, tedious, extensive, time-consuming! But more than that, I feel negatively about scientific writing because it is primarily formulaic, and exceptionally passive! In my field, there is incredible overuse of terms such as: "suggests", "implies", "may illustrate", "tends to", "may explain", etc. Of course, there is a core tenet of science which has cultivated this writing style, that nothing in science is ever "proven". In the sport science literature, there are few who actively push the envelope to state their own thoughts and ideas. Those that do are almost always the established researchers with a significant body of work and literature behind them. But it is my opinion that even early career researchers have independent and valid thoughts, substantiated by their reading, research findings and experience, which they should be encouraged to express more assertively.

3. The formula can serve as a bit of a cheat's way of getting started. Though specific sub-headings develop over time, I find that the generic "rationale/aims & hypotheses/methodology/results/discussion/conclusion" subheadings are, at the very least, a starting point for categorising references, as well as my own thoughts and ideas. Most of my positive feelings about academic writing come about at completion ;)
