---
title: "60-Day PhD Writing Challenge Day 4: Listing your revision/writing tasks"
author: "Jacquie Tran"
date: "2011-06-03"
categories:
  - phd
  - phd tumblr support group
  - phd writing
---

**Day 4: Listing your revision/writing tasks.**

My writing plan started back in mid-April and is 11 weeks long in total, which places me at week 7 right now. I submitted a first draft of my literature review and research proposal two weeks ago

Broad goals for remaining weeks:
**Week 7:** Work on second draft.
**Week 8:** Submit second draft to supervisors.
**Week 9:** Work on third draft.
**Week 10:** Submit third draft to supervisors.
**Week 11:** Submit final documents to supervisors on June 30.

Weekly writing tasks:
**Week 7:** Address feedback, continue to develop key arguments, write section-by-section, refine methodology.
**Week 8:** Write section-by-section, refine methodology (especially statistical analyses), edit for flow.
**Week 9:** Address feedback, add additional content to literature review and research proposal if appropriate.
**Week 10:** Edit for flow, finalise research plan.
**Week 11:** "Attention to detail" - spelling, grammar, abbreviations, glossary, tables and figures, formatting, etc...
